/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./src/components/Layout/AddButton.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Calendar: typeof import('./src/components/TimeSystem/Calendar/Calendar.vue')['default']
    CusinNode: typeof import('./src/components/PlanningSystem/CusinNode.vue')['default']
    CusoutNode: typeof import('./src/components/PlanningSystem/CusoutNode.vue')['default']
    CustomNode: typeof import('./src/components/PlanningSystem/CustomNode.vue')['default']
    DeleteConfirmDialog: typeof import('./src/components/PlanningSystem/DeleteConfirmDialog.vue')['default']
    EditEventForm: typeof import('./src/components/TimeSystem/Calendar/EditEventForm.vue')['default']
    EditToDoForm: typeof import('./src/components/TimeSystem/ToDo/EditToDoForm.vue')['default']
    Gantt: typeof import('./src/components/TimeSystem/Gantt.vue')['default']
    NewEventForm: typeof import('./src/components/TimeSystem/Calendar/NewEventForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    Sortable: typeof import('./src/components/Sortable/Sortable.vue')['default']
    SortableItem: typeof import('./src/components/Sortable/SortableItem.vue')['default']
    StatePlanning: typeof import('./src/components/PlanningSystem/StatePlanning.vue')['default']
    StatePlanningForm: typeof import('./src/components/PlanningSystem/StatePlanningForm.vue')['default']
    Stepper: typeof import('./src/components/ui/stepper/Stepper.vue')['default']
    StepperDescription: typeof import('./src/components/ui/stepper/StepperDescription.vue')['default']
    StepperIndicator: typeof import('./src/components/ui/stepper/StepperIndicator.vue')['default']
    StepperItem: typeof import('./src/components/ui/stepper/StepperItem.vue')['default']
    StepperSeparator: typeof import('./src/components/ui/stepper/StepperSeparator.vue')['default']
    StepperTitle: typeof import('./src/components/ui/stepper/StepperTitle.vue')['default']
    StepperTrigger: typeof import('./src/components/ui/stepper/StepperTrigger.vue')['default']
    ToDo: typeof import('./src/components/TimeSystem/ToDo/ToDo.vue')['default']
    ToDoContainer: typeof import('./src/components/TimeSystem/ToDo/ToDoContainer.vue')['default']
    WatermarkPanel: typeof import('./src/components/Layout/WatermarkPanel.vue')['default']
  }
}
